name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y cmake zlib1g-dev \
            libgl1-mesa-dev libx11-dev libxrandr-dev \
            libxinerama-dev libxcursor-dev libxi-dev \
            libasound2-dev libwayland-dev libxkbcommon-dev

      - name: Cachear dependencias de CMake (Raylib)
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: linux-deps-${{ hashFiles('CMakeLists.txt') }}

      - name: Configurar
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Compilar
        run: cmake --build build -j$(nproc)
